### ISSUE TITLE
Final changes to make for 0.6 release

### ISSUE THREAD

**Issue by jleong-openedx** [ubc/ubcpi#107]
From meeting on Monday, November 07, to go over new features for this release and determine final changes to make:

- [x] emphasize question heading and text (for use with progress bar)
- [x] consider changing anchoring in different stages; implemented for on-click of "Next Step"
- [x] change both initial and final answer in results to the same colouring
- [x] remove graph headings at bottom of graphs
- [x] remove rationale "correct answer" caption for case where there is no correct answer
- [x] change text in studio view to "sees the correct answer, if supplied, and any explanation that you provide for it"; and also: "sees the answers and explanations provided by other learners"
- [x] change "rationale" in top blurb in studio view to "explanation"
- [x] add "or select "n/a" if there is no correct answer" in studio view
- [x] change first sentence in top blurb in studio view to include "a multiple choice question that may or may not have a correct answer"
- [x] put progress bar back in for studio view
- [x] final wording changes TBD; put all changes in place
- [x] make final decision with all stakeholders on name change; decided on "Peer Rationale Reflection Tool."

**Comment by lenglund** [comment]
Proposal for introductory text wording changes...

Peer-Based Reflection Tool

Peer-based reflection problems give learners more interactive engagement while they complete a multiple choice question that may or may not have a correct answer. The tool supports deeper consideration of the learner’s understanding of a concept and the correctness (if applicable) of an initial answer. Learners complete these problems in three steps.

First, the learner answers a multiple choice question and provides an explanation for the answer. Next, the learner sees answers and explanations submitted by other learners. After reflecting on these peer responses, the learner can make revisions and resubmit an answer and explanation. Finally, the learner sees the correct answer, if supplied, and any explanation that you provided for it.

**Comment by jleong-openedx** [comment]
The introductory text wording changes are now in place.

**Comment by jleong-openedx** [comment]
All these are now in place for [release 0.6](https://github.com/ubc/ubcpi/releases/tag/0.6.0).
