### ISSUE TITLE
Can't git fetch because of branch `0.6/justin`

### ISSUE THREAD

**Issue by bryanlandia** [ubc/ubcpi#117]
The branch doesn't appear in GitHub but it's there.
```
pip install -vvv -e git+https://github.com/ubc/ubcpi@4ee35208759ce7a27f0617b14f433a78e019d380#egg=ubcpi-xblock
Obtaining ubcpi-xblock from git+https://github.com/ubc/ubcpi@4ee35208759ce7a27f0617b14f433a78e019d380#egg=ubcpi-xblock
  Running command git config remote.origin.url
  https://github.com/ubc/ubcpi
  Clone in /edx/app/edxapp/venvs/edxapp/src/ubcpi-xblock exists, and has correct URL (https://github.com/ubc/ubcpi)
  Updating /edx/app/edxapp/venvs/edxapp/src/ubcpi-xblock clone (to 4ee35208759ce7a27f0617b14f433a78e019d380)
  Running command git fetch -q
error: there are still refs under 'refs/remotes/origin/0.6'
  Complete output from command git fetch -q:
  
  ----------------------------------------
Cleaning up...
Command "git fetch -q" failed with error code 1 in /edx/app/edxapp/venvs/edxapp/src/ubcpi-xblock
```

**Comment by xcompass** [comment]
It works on my local environment. I guess I probably don't have the 0.6/justin branch in the first place. Could you remove the 0.6/justin branch in your /edx/app/edxapp/venvs/edxapp/src/ubcpi-xblock and try again?

**Comment by bryanlandia** [comment]
Thanks for the reply, Pan.  I actually don’t have the 0.6/justin branch locally.

**Comment by xcompass** [comment]
That's weird. Did you solve it yet? If not, could you try to remove the   /edx/app/edxapp/venvs/edxapp/src/ubcpi-xblock directory. It seems something preventing it to be updated. If you remove it, git should make a new clone.

**Comment by jleong-openedx** [comment]
Hi @bryanlandia, we are closing this for now; please let us know if you have further questions/issues.
