### ISSUE TITLE
span elements cannot be siblings of li elements

### ISSUE THREAD

**Issue by cptvitamin** [ubc/ubcpi#122]
The [commit message](https://github.com/ubc/ubcpi/commit/066e0128f44bd4ec4c12e2467f63e65fc989abe9) says "Move spans within lis" but as can be seen on[ line 26 and 28, 59 and 61, and 162 and 164](https://github.com/ubc/ubcpi/commit/066e0128f44bd4ec4c12e2467f63e65fc989abe9#diff-cb1f4d6365b43167a8da7a0894a1242dR26) of ubcpi/static/html/ubcpi.html, this has not been done.

The only valid children of an ```<ol>```  element are ```<li>```  elements.

**Comment by xcompass** [comment]
@jleong-openedx could you take a look? Thanks.

**Comment by jleong-openedx** [comment]
Thanks @cptvitamin, [this commit](https://github.com/ubc/ubcpi/commit/d02381324c7e5e66966078c6b64be1f929a0d683) fixes this.

**Comment by jleong-openedx** [comment]
Fixed by #124.
