### ISSUE TITLE
LaTeX or MathML support for PI Tool ?

### ISSUE THREAD

**Issue by firasm** [ubc/ubcpi#139]
Hello everyone,

thought I'd post here to ask if anyone has any suggestions or workarounds for using LaTeX in the question choices in the PI tool ?

Trying to run a study in the physics course with Ido and Jared but having lots of difficulties trying to get things to show up nicely.

I thought I'd be clever and use pictures of the answer choices but it takes up SO much real-estate (and they look horrible, all at different sizes). 

![screen shot 2017-10-12 at 12 20 50 pm](https://user-images.githubusercontent.com/2507459/31515262-67e00ce2-af49-11e7-9d9e-60be04d9cc77.png)

**Comment by jleong-openedx** [comment]
Hi @firasm, unfortunately there is not currently a better option for this in Peer Instruction. We do have future plans to extend Peer Instruction functionality beyond plain text and images, although I cannot provide an estimate on this.

**Comment by lenglund** [comment]
Noted in existing issue #10.
