### ISSUE TITLE
Consider ways to improve visual consistency of answers throughout

### ISSUE THREAD

**Issue by lenglund** [ubc/ubcpi#144]
Answers initially appear vertically and in a set order. Can this remain more consistent, e.g., peer answers are sorted in the same order, histogram data is presented in the same orientation/order?

**Comment by lenglund** [comment]
Could also consider another way of visual matching between options and answers, e.g., colour coding.

**Comment by lenglund** [comment]
Mockups for discussion at next meeting:

Pre-selection:
![step1a](https://user-images.githubusercontent.com/6118592/35876499-56434bf4-0b27-11e8-99a7-8abc918a7d75.png)

Selecting progressively reveals explanation textbox:
![step1b](https://user-images.githubusercontent.com/6118592/35876501-5665fa5a-0b27-11e8-9eb5-b53f8dc3d95b.png)

Explanation enables next button:
![step1c](https://user-images.githubusercontent.com/6118592/35876502-568b9ff8-0b27-11e8-9923-fa869e97c913.png)

Next step:
![step2a](https://user-images.githubusercontent.com/6118592/35876504-56af9d72-0b27-11e8-9ee8-b84fba56874e.png)

After clicking to edit:
![step2b](https://user-images.githubusercontent.com/6118592/35876505-56d150de-0b27-11e8-97a0-47ed1269a93a.png)

If selection changed:
![step2c](https://user-images.githubusercontent.com/6118592/35876506-56f03bac-0b27-11e8-818c-56f6cd7ed6d6.png)

Explanation updated:
![step2d](https://user-images.githubusercontent.com/6118592/35876507-57197774-0b27-11e8-9236-09ea3ce522d7.png)

Next step:
![step3](https://user-images.githubusercontent.com/6118592/35876508-573cdb42-0b27-11e8-93e5-da80b5b2dfee.png)

Alternate view if no correct answer:
![step3alt](https://user-images.githubusercontent.com/6118592/35876509-575ea326-0b27-11e8-84d3-804b95940230.png)

**Comment by lenglund** [comment]
Change step headings to:
Step 1) Give Initial Answer
Step 2) Read Other Student Answers
Step 3) View Course-Wide Results

Change edit answer button to:
Revise Answer

Use stronger text for text on top of graphs (hard to read as-is in mockups).

**Comment by jleong-openedx** [comment]
Please see the [fix-62-focus-student-engagement](https://github.com/ubc/ubcpi/tree/fix-62-focus-student-engagement) branch; currently, showing the rationale text area upon selecting an option is implemented.

(For interest's sake, pull request #137 contains the complete implementation for issue #62; this issue (#144) represents updates to implement, based on the original changes made for issue #62.

**Comment by lenglund** [comment]
See branch and issue #62 for background and possible code to re-use in implementing this.

**Comment by kitsook** [comment]
When there is no correct answer, instructor's explanation will be displayed on top of the options.

![image](https://user-images.githubusercontent.com/13360325/38759859-c57610ae-3f2c-11e8-9889-ba856ff705c9.png)
