### ISSUE TITLE
UBCPI Trasnlations do not get picked up by Django

### ISSUE THREAD

**Issue by llasha** [ubc/ubcpi#154]
I am using open-release/hawthron.master (native install), and I have a problem with translated strings (in any languages) showing in either LMS and CMS.
These are the steps I followed:

1. I have added new translations for 'ubcpi' to third party installed apps in
/edx/edx-platform/conf/locale/config.yaml

third_party:
   - wiki
   - edx_proctoring_proctortrack.po
   **- ubcpi**
....
generate_merge:
    django.po:
        - django-partial.po
        - django-studio.po
        - mako.po
        - mako-studio.po
        - wiki.po
        - edx_proctoring_proctortrack.po
       **- ubcpi**
    djangojs.po:
        - djangojs-partial.po
        - djangojs-studio.po
        - underscore.po
       - underscore-studio.po
       **- ubcpi**
2. After running
i18n_tool extract
i18n_tool generate

and compiling assets (python manage.py lms compilejsi18n --settings=aws --packages=ubcpi), I got all files copied to /edx/var/edxapp/staticfiles/ubcpi

Yet, translations are not showing up in either LMS or CMS. I tried other languages, too in which UBCPI is already translated, since the translated strings are not showing up in either LMS ior CMS.

**Comment by morenol** [comment]
The translations of this xblock are resolved in https://github.com/ubc/ubcpi/blob/master/ubcpi/static/js/src/translations.js, so we cannot override them from django.

If you want to add a new language, maybe you should add that to this line https://github.com/ubc/ubcpi/blob/998a52f5afc7338d858250579f40b4563a889750/Makefile#L63

translate the project in transifex,
and the run make pull_translations.
