### ISSUE TITLE
Peer Instruction exercise is deleted on import if it contains Correct Answer = N/A

### ISSUE THREAD

**Issue by awaisdar001** [ubc/ubcpi#156]
### Reproduction Setup
A. As an instructor in the studio, enable "ubcpi" and add a peer instruction question in the courseware. Docs: https://edx.readthedocs.io/projects/edx-partner-course-staff/en/latest/exercises_tools/peer_instruction_tool.html?highlight=peer%20instruction#enable-the-peer-instruction-toolB. Edit the component, scroll down to "Correct Answer" and select "n/a". Delete all text in the optional explanation section. Save and publish.C. Export the course .tar.gz. Optional: You can unpack it and search the files for "<ubcpi url_name"..., verifying that the component was exported.

### Observe 
A. Import the .tar.gz

2. Expected behavior: The imported course contains the original peer instruction exercise.3. Observed behavior: The imported course has deleted the peer instruction component. Optional: you can re-export the course, and observe that the entire "<ubcpi" content block is missing from the vertical now.

5. Business value: Silently deleting fully-supported, studio-authored content means teams could be losing data without realizing it; undermines confidence in Studio and how it handles content.

6. Additional Info: The Harvard team found this bug and described a workaround. However, it needs to be applied before the bug is encountered, so course teams need knowledge that the bug exists."We were able to work around this by designating a correct answer and adding an explanation to each component prior to import. Then I went through and switched the “answer” back to “n/a” and deleted the explanation for each Peer Instruction Question once they were back in the course."

### Fix
I have created a PR for the fix here, I am not sure whom to tag for the review. 
https://github.com/ubc/ubcpi/pull/155/files

**Comment by fysheets** [comment]
Hello,

I would like to +1 this issue. We had this error reported at edX while using this XBlock. We would love to continue the conversation to try to get a resolution in place. Please let us know if there are any questions or concerns.

Thanks!

**Comment by DawoudSheraz** [comment]
@kitsook We would like to have this issue and PR in question merged as it has been opened for quite a while and there has been no response. Thanks

**Comment by sethmccann** [comment]
@richardtape, @xcompass, Any chance you can review this issue and PR?
Thank you,
Seth

**Comment by awaisdar001** [comment]
https://github.com/ubc/ubcpi/pull/155 has been merged successfully, I am closing this.
