### ISSUE TITLE
Publish v0.6.5 on PyPI

### ISSUE THREAD

**Issue by stvstnfrd** [ubc/ubcpi#157]
It looks like the version was bumped in code to `v0.6.5` [1]
but the most recent published version on PyPI is `v0.6.4` [2].

Would you mind publishing the latest version on PyPI?
We use this at Stanford and appreciate the work!
Thanks!

- [1] https://github.com/ubc/ubcpi/commit/7b6de03f93f3a4a8af4b92dfde7c69eeaf21f46e
- [2] https://pypi.org/project/ubcpi-xblock/#history

**Comment by xcompass** [comment]
Thanks Steve. Just pushed 0.6.5 to PyPI.
