### ISSUE TITLE
Juniper compatibility

### ISSUE THREAD

**Issue by toxinu** [ubc/ubcpi#170]
Hi there,

I wanted to know if `ubcpi` xBlock is already Juniper (Python 3 and Django 2.2) compatible and if not, is there any plan to update it for Juniper? Or are you open to contributions?

Thanks.

cc @richardtape @xcompass

**Comment by xcompass** [comment]
We haven't test it and we don't have any plan to update it for Juniper. If you are interested, we are welcome for the contributions.

**Comment by toxinu** [comment]
Thanks for your reply @xcompass. 😃
