### ISSUE TITLE
Unit Test for javascript

### ISSUE THREAD

**Issue by richardtape** [ubc/ubcpi#23]
Need unit tests for both the ubcpi.js and ubcpi-edit.js. The current jasmine test we have is from an incredibly early stage and is out-of-date.

We're going to use Karma, so we'll need to get that set up first

## karma setup

* [x] package.json setup ( similar to https://github.com/edx/edx-ora2/blob/master/package.json )
* [x] karma.conf.js setup ( similar to https://github.com/edx/edx-ora2/blob/master/karma.conf.js )

## ubcpi-edit.js

* [x] Test validation allowing submit button
* [x] Test max and min characters

## ubcpi.js

* [x] Test statuses
* [x] Test chat creation

TODO: List more JS Tests

**Comment by xcompass** [comment]
Done.
