### ISSUE TITLE
Unit Tests for python

### ISSUE THREAD

**Issue by richardtape** [ubc/ubcpi#24]
We don't have any python unit tests currently.

## ubcpi.py

* [ ] Test `get_student_item_dict()` produces a valid student dict
* [ ] Test `get_asset_url()` produces an appropriate url
* [ ] Test `studio_view()` returns a valid `frag`
* [ ] Test `studio_submit()` returns success when appropriate
* [ ] Test `student_view()` returns valid `frag`
* [ ] Test `record_response()` publishes grade appropriately
* [ ] Test `get_grade()` returns a valid grade
* [ ] Test `submit_answer()` returns a valid `ret` object
* [ ] Test `get_answers_for_student()` returns a valid response
* [ ] Test `validate_form()` returns appropriate responses
* [ ] Test `validate_options()` returns appropriate error objects

## persistence.py

* [ ] Test `get_answers_for_student()` returns an appropriate `Answers` object

## answer_pool.py

* [ ] Test `offer_answer()` returns appropriate response given set algorithm names
* [ ] Test `offer_simple()` gives expected pool
* [ ] Test `offer_random()` gives expected pool
* [ ] Test `validate_seeded_answers_simple()` validates appropriately
* [ ] Test `validate_seeded_answers_random()` validates appropriately
* [ ] Test `validate_seeded_answers()` handles appropriate algo names
* [ ] Test `get_other_answers()` gets answers based on algo names
* [ ] Test `get_other_answers_simple()` gets other answers as expected
* [ ] Test `get_other_answers_random()` gets random answers as expected
* [ ] Test `convert_seeded_answers()` converts seeded answers appropriately

**Comment by richardtape** [comment]
There's a [document on how edX expects unit tests](https://github.com/edx/edx-platform/blob/master/docs/en_us/internal/testing.rst) which lists [https://docs.python.org/2/library/unittest.html](https://docs.python.org/2/library/unittest.html) as the way they expect python tests to be done

**Comment by xcompass** [comment]
I'm in the process of setting up the test environment for xblock python part.

**Comment by xcompass** [comment]
Done in b961d8b886d090c9369d31fefeaad932a1ba0b91
