### ISSUE TITLE
The problems don't appear to be scorable

### ISSUE THREAD

**Issue by xcompass** [ubc/ubcpi#34]
The problems don't appear to be scorable, even if I put them into a graded unit. I can't remember - is that intentional? I would imagine some course instructors may want to be able to assign points to completion of the block.

**Comment by richardtape** [comment]
Didn't we remove the scoring code from the released version?

**Comment by xcompass** [comment]
I added back in. We do want it to be scored. Though I thought it was
working before.

**Comment by richardtape** [comment]
Oh. Maybe I'm getting confused but: https://github.com/ubc/ubcpi/blob/master/ubcpi/ubcpi.py#L209

**Comment by richardtape** [comment]
Two different ways to score;

1) Completion
2) Correct Answer

Need an interface piece to give the instructor the possibility to choose this

**Comment by xcompass** [comment]
enabled in 0.5.0
