### ISSUE TITLE
Unit Tests failing on missing module

### ISSUE THREAD

**Issue by richardtape** [ubc/ubcpi#36]
```
File "/edx/app/edxapp/venvs/edxapp/src/edx-sga/edx_sga/sga.py", line 16, in <module>
    from courseware.models import StudentModule
ImportError: No module named courseware.models
```

This seems to be output for every test and makes finding the 3 failing unit tests really tricky.

**Comment by xcompass** [comment]
How did you run the tests? It seems you are running wrong tests.

**Comment by richardtape** [comment]
I ran `make test` from within the xblock directory as per the readme instructions. Running `make test-js` gives me expected output, however.

**Comment by xcompass** [comment]
Are you in your python virtual env for ubcpi?

**Comment by richardtape** [comment]
I was, yeah. After a pull, the tests now run, but the error still exists.
