### ISSUE TITLE
Some feedbacks for UX

### ISSUE THREAD

**Issue by xcompass** [ubc/ubcpi#44]
Here are some suggestions for the text that appears in the UI, both in the problem template and in the labels and help string in Studio and the LMS. I would categorize all of them as "nits".

In the component editor in Studio, I think it might be helpful to expand the problem template a little bit, with an orienting "what is this?" type of sentence. and a little more detail about the three steps that learners experience. I drafted this up as an example of what I mean... 

<p>Peer instruction problems give learners an opportunity for interactive engagement while they answer a multiple choice question. Learners complete these problems in three steps. </p>
<p>First, the learner answers a multiple choice question and provides a rationale for the answer. Next, the learner sees the rationale provided by another learner for each of the other possible answers. After assessing this input, the learner can make revisions and resubmit an answer and rationale. Finally, the learner sees the correct answer and the rationale that you provide for it. </p>
<p>Where does most of the mass in a fully grown tree originate?</p>
 
For the labels, options, and help strings in the Studio component editor and in the LMS, there are some instances where the capitalization is off, or punctuation missing, little things like that. I can do a thorough copy edit if you want me to, but here are some general suggestions if you want/have time to make a pass through to do that kind of nit-picky cleanup.
Use complete sentences, with sentence capitalization and punctuation, for the help strings. For example, (You may change this response if you wish in the next step) should have a period after "step".
In the LMS, the labels appear in differently sized fonts. For example, in the first step, "Your Response" is larger than "Please explain your selection". I'd suggest using a consistent look for the labels.
In other Studio components, such as multiple choice problems, the help strings appear below both the label and its control, and they extend across the width of the modal. In this PI XBlock, the help strings are limited to the width of the space below the labels. I'd suggest presenting the help strings in the same way as the existing "basic" problem components.
Similarly, there's no need to use italic font for the help text in Studio. 
Capitalize the options in dropdown lists. For example, the Selection Algorithm dropdown in Studio should have options for Simple or Random rather than simple or random.

**Comment by xcompass** [comment]
cc @lamagnifica

**Comment by richardtape** [comment]
Hi @lamagnifica thanks so much for this feedback. Having someone go through the XBlock with a fine tooth-comb is invaluable. I'm just in the process of making the amendments you've suggested - I've just got to

> In other Studio components, such as multiple choice problems, the help strings appear below both the label and its control, and they extend across the width of the modal. In this PI XBlock, the help strings are limited to the width of the space below the labels. I'd suggest presenting the help strings in the same way as the existing "basic" problem components.

Initially, we had mirrored the layout and styling of the basic components. However, as we have some nested repeater fields - which need some explanation - (And after some internal confusion over these fields) we settled on having the hints below the labels for these fields. For our users, this seemed to solve their issues. We were hoping that it was an acceptable compromise which benefitted the user and was also close-enough to the basic components that it still felt native.

If, having heard this, you'd still prefer us to mirror the basic components, I'm happy to do this, I was just hoping to give you a little more context on why we made that decision.

**Comment by lamagnifica** [comment]
@richardtape glad you find the suggestions useful. I suspected that the layout of the sections for options and seeds might have guided the two-column format, with help under the label. I think that's fine.
I have additional suggestions for revising the help strings from a PID point of view (progressive information disclosure, which is a strategic approach to presenting guidance to software users). Should I email them to you, added to the message that Pan quoted above?

**Comment by richardtape** [comment]
That's great, thanks @lamagnifica

Whichever method is easiest for you - here in this ticket if appropriate 
or via email ( richard dot tape -at- ubc -dot- ca )

PID is new to me, so I'm looking forward to see where and how we can 
make improvements.

Alison Hodges wrote:

**Comment by lamagnifica** [comment]
Apologies @richardtape and @xcompass I have been unable to get back to the PID review. I will send suggestions for your consideration by email, and hope to be able to do that by the end of this week.
