### ISSUE TITLE
Student Usability Testing - Suggested changes to student front end

### ISSUE THREAD

**Issue by lenglund** [ubc/ubcpi#47]
Based on student usability testing conducted in early November, the following changes are suggested. 

First state UI
![peer instruction - step 1](https://cloud.githubusercontent.com/assets/6118592/11382853/2abe0052-92b9-11e5-977d-cde79ea3fdf3.png)

Second state UI
![peer instruction - step 2-3](https://cloud.githubusercontent.com/assets/6118592/11382852/2abdbdb8-92b9-11e5-842b-d5cd8f5bb291.png)

Third state UI
![peer instruction - step 4](https://cloud.githubusercontent.com/assets/6118592/11382851/2abc4640-92b9-11e5-8954-b4f789333131.png)

These changes will help resolve confusion around the primary pain points students encountered. These pain points included not understanding the second state, not interpreting the graphs correctly, not reading/understanding the other student answers, not being able to scan the content easily, and not knowing which "next" button to choose.

**Comment by richardtape** [comment]
This is awesome. Thanks so much, Letitia! We've made some minor 
amendments to the UI in the LMS since early Nov. but much of this we can 
definitely incorporate.

> Letitia <mailto:notifications@github.com>
> November 24, 2015 at 2:44 PM
>
> Based on student usability testing conducted in early November, the 
> following changes are suggested.
>
> First state UI
> peer instruction - step 1 
> <https://cloud.githubusercontent.com/assets/6118592/11382853/2abe0052-92b9-11e5-977d-cde79ea3fdf3.png>
>
> Second state UI
> peer instruction - step 2-3 
> <https://cloud.githubusercontent.com/assets/6118592/11382852/2abdbdb8-92b9-11e5-842b-d5cd8f5bb291.png>
>
> Third state UI
> peer instruction - step 4 
> <https://cloud.githubusercontent.com/assets/6118592/11382851/2abc4640-92b9-11e5-8954-b4f789333131.png>
>
> These changes will help resolve confusion around the primary pain 
> points students encountered. These pain points included not 
> understanding the second state, not interpreting the graphs correctly, 
> not reading/understanding the other student answers, not being able to 
> scan the content easily, and not knowing which "next" button to choose.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/ubc/ubcpi/issues/47>.
>

-- 
Sent from Postbox 
<https://www.postbox-inc.com/?utm_source=email&utm_medium=siglink&utm_campaign=reach>
