### ISSUE TITLE
Allow course staff to see statistics without completing exercise

### ISSUE THREAD

**Issue by whider** [ubc/ubcpi#59]
Currently, staff need to complete the exercise in order to see the statistics. Need way of giving direct access to the results.

**Comment by richardtape** [comment]
`role = self.xmodule_runtime.get_user_role()`

is how to get the current user's role.

**Comment by richardtape** [comment]
https://github.com/ubc/ubcpi/tree/fix-59-instructor-charts

First pass at displaying the graphs when it's an instructor, so they don't have to wait for 10 results. Need to be able to skip directly to this step.

**Comment by bpickard** [comment]
Fixed in PR #85.
