### ISSUE TITLE
Hook up to the grading system

### ISSUE THREAD

**Issue by richardtape** [ubc/ubcpi#6]
Grading options - completion grade or grade for correct answer

**Comment by richardtape** [comment]
https://openedx.atlassian.net/wiki/display/TNL/edX+Grading+Guide+for+Developers is an overview of how grades work within edX

**Comment by xcompass** [comment]
:+1:

**Comment by richardtape** [comment]
And this is a very basic rundown of what an xblock has to do to participate in the grades system:

https://github.com/edx/edx-documentation/blob/master/en_us/developers/source/extending_platform/xblocks.rst#grading

> To participate in the course grade, an XBlock should set has_score to True, and should publish a grade event whenever the grade changes.

**Comment by richardtape** [comment]
And finally, https://github.com/pmitros/DoneXBlock is an example of how a student can mark something as 'Done' and it hooks up to the `grade system` at 

https://github.com/pmitros/DoneXBlock/blob/cf3033918e767853791a407917f7f56cafb1d50c/done/done.py#L28 

and `publishes a grade event` at 

https://github.com/pmitros/DoneXBlock/blob/cf3033918e767853791a407917f7f56cafb1d50c/done/done.py#L48

**Comment by richardtape** [comment]
https://github.com/ubc/ubcpi/commit/8da8b3bc8a8d9ebee327a6ce95bfce5f25402794 adds a first pass at hooking up UBCPI with a simple grading mechanism. When a student submits their response for a second time, they are given the grade (1) regardless of the answer being correct or not. It's more like a 'completion' grade.
