### ISSUE TITLE
Check how the warning for the character limits appears

### ISSUE THREAD

**Issue by xcompass** [ubc/ubcpi#67]
The pale yellow note below the explanation box changes if my text is too long, but the student won’t notice this.  And the change doesn’t actually say that the text is too long.

And the changed text is awkward: "Note: Your rationale must be at most 500 characters. Note: In order to move to the next step please explain your selection.”

Better:  "Note: In order to move to the next step you need to briefly explain why you chose this answer.  This explanation must be at most 500 characters."

Also, put this note before the description of the next step.

**Comment by xcompass** [comment]
Display the limit if it's over

**Comment by bpickard** [comment]
Fixed in PR #76.

Notes: Currently the warning displays if you have less then 1/10th of the character limit left. These types of warnings don't exist in other question types at current so this should be reviewed.
