### ISSUE TITLE
i18n support for peer instruction tool

### ISSUE THREAD

**Issue by asadiqbal08** [ubc/ubcpi#79]
Need to mark all possible strings for translation in Peer Instruction tool and mark them for translations using runtime service. 
We had made some [changes](https://github.com/edx/edx-platform/pull/11575) against a ticket [WL-315](https://openedx.atlassian.net/browse/WL-315) in edx-platform to support the issue.

**Comment by richardtape** [comment]
Hey @asadiqbal08 

Thanks so much for the issue and the PR. We have an [issue](https://github.com/ubc/ubcpi/issues/69) open for i18n support so it's definitely been on our radar. We've been tracking the issue you linked before moving on this as it was apparent that positive changes were happening. We'll review your PR and get back to you. I'll close the other issue as we can converse in here.

It looks like the unit tests failed in your [PR](https://github.com/ubc/ubcpi/pull/80). We can take a look at those if you don't get the time.

**Comment by mattdrayer** [comment]
Hi @richardtape!  Thanks much for jumping on this one so quickly -- we have a pending change in the XBlock core repo that will probably merge tomorrow, and it should help to address the unit test failure.  We'll keep you posted!

**Comment by mattdrayer** [comment]
This PR has been replaced by an updated change set found in #81.  I am going to close this PR now.
