### ISSUE TITLE
Orientation lost when advancing to next step

### ISSUE THREAD

**Issue by lenglund** [ubc/ubcpi#88]
Users can get disoriented when moving from one step to another; there isn't an indication this is a wizard-like experience. Options:
- [x] Make the transition from one step to another more deliberate and/or
- [x] Implement a progress bar at the top of the component with steps and text that appears throughout the exercise to show the users where they are in the process

**Comment by lenglund** [comment]
Attaching rough mockups. Feel free to improve when implementing! For placement, it made more sense when actually looking at it to have the progress *after* the question, as this is where we "start" for each step.
![proposed-progress-bar-2](https://cloud.githubusercontent.com/assets/6118592/19009321/6e4c8fce-8727-11e6-8df1-ddabdfda7cd5.png)
![proposed-progress-bar](https://cloud.githubusercontent.com/assets/6118592/19009322/6e52b372-8727-11e6-8bca-d79b5cb8c540.png)

Code with inline styles as used to create the HTML mockup (for reference only):

<ul style="background:#f8f8f8;border:2px solid #ddd;margin:1em 0;padding-top:.3em;text-transform:uppercase;">
  <li style="display:inline-block;width:30%;text-align:center;font-weight:bold;color:#333;padding-top:.3em"><i class="fa fa-arrow-circle-down" style="font-size:1.4em;"></i></span><br>Answer</li> 
  <i class="fa fa-angle-double-right" style="color:#ddd;vertical-align:15%;font-size:2.2em"></i>
  <li style="display:inline-block;width:30%;text-align:center;color:#aaa;padding-top:.3em;text-transform:uppercase;"><i class="fa fa-circle-o" style="font-size:1.4em;"></i><br>Reflection</li>
  <i class="fa fa-angle-double-right" style="color:#ddd;vertical-align:15%;font-size:2.2em"></i>
  <li style="display:inline-block;width:30%;text-align:center;color:#aaa"><i class="fa fa-circle-o" style="font-size:1.4em;"></i><br>Results</li>
</ul>

Checked icon is class fa-check-circle.

**Comment by jleong-openedx** [comment]
This has been implemented in #103, which has been merged into [0.6](https://github.com/ubc/ubcpi/tree/0.6).
