### ISSUE TITLE
Allow instructor setup PI question without a correct answer

### ISSUE THREAD

**Issue by xcompass** [ubc/ubcpi#90]
Some of the question may not have a correct answer. This feature allow instructor to setup the PI question without specify the correct answer. The statistic graph on the final stage should not highlight any answer as well if this option is specified. (from Ido)

**Comment by jleong-openedx** [comment]
Reopened for additional tasks from Fri Sept 30 meeting:

Studio view:
- [ ] Change "No correct answer" to "n/a" in the drop-down box for Correct Answer
- [ ] Change explanatory text for Explanation field to "Students see the explanation after seeing the final answer."
- [ ] Indicate, for each field, that a value must be selected/entered by appending a space then a red asterisk to each field label
- [ ] Indicate, for the Explanation field, that a value is optional only when "n/a" is selected for the Correct Answer field

Student view:
- [ ] Add "Instructor's explanation" as a header label to the final screen for instances where there is no correct answer and the instructor has provided a rationale
- [ ] Change both initial and final answers to black on the final screen, for instances where there is no correct answer

**Comment by jleong-openedx** [comment]
This has been implemented in #98 and #106, and merged into [0.6](https://github.com/ubc/ubcpi/tree/0.6).
