### ISSUE TITLE
Revisit how graphs are displayed

### ISSUE THREAD

**Issue by xcompass** [ubc/ubcpi#93]
Currently always display histogram (from Ido) - create option to hide

**Comment by jleong-openedx** [comment]
This looks to be appropriate as a setting in Studio e.g. the instructor can specify "Yes" or "No" for a "Show Histogram" setting.

**Comment by lenglund** [comment]
Per discussion today: Hiding graphs means step 3 may be empty. Consider instead combining graphs into one, possibly combining with legend.
