### ISSUE TITLE
Remove ubc from the name

### ISSUE THREAD

**Issue by xcompass** [ubc/ubcpi#97]
In order to make the tool generic, we need to remove ubc from the name. We need to come up with a name.

**Comment by jleong-openedx** [comment]
We have decided on:

Peer Rationale Reflection Tool

To avoid breaking existing instances of Peer Instruction, we are keeping the module name (ubcpi) the same; this will only show up under Settings->Advanced Settings->Advanced Module List. Only the individuals configuring advanced modules/components will have to view this.

The new name is in place and titles, headings etc have been changed for [release 0.6](https://github.com/ubc/ubcpi/tree/0.6).
