### ISSUE TITLE
Error: 'PeerInstructionXBlockWithMixins' object has no attribute 'ugettext' 

### ISSUE THREAD

**Issue by nachotheix** [ubc/ubcpi#99]
OpenEdx Version: DogWood.3  (Language: es_419)
ubc-xblock version: 0.5.3

Error: 'PeerInstructionXBlockWithMixins' object has no attribute 'ugettext' 

File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/ubcpi/ubcpi.py", line 444, in student_view
    'display_name': self.ugettext(self.display_name),

I haved removed self.ugettext from this line ... but this error appears again when I edit a component.

Thanks.

**Comment by xcompass** [comment]
Hi @nachotheix , sorry for the delay. It looks like you got a version miss match. If you are running dogwood, you may need to run ubcpi 0.5.1. The internationalization feature is added in 0.5.2, which is based on xblock version 0.4.7. Unfortunately, the dogwood release only have xblock version 0.4.4.
